# Generated by Django 6.0.4 on 2026-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='kategori',
            field=models.CharField(default='Umum', max_length=100),
            preserve_default=False,
        ),
    ]
